# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONUNBUFFERED: "True"
      UV_LINK_MODE: "copy"
      ADVENT_RUN_ALL_TESTS: "True"

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"
          python-version: "3.13"

      - name: Install Dependencies
        run: uv sync
        shell: bash

      - name: Code Quality
        run: |
          uv run pyright .
          uv run ruff check .
          uv run ruff format . --check --diff

      - name: Unit Tests (All Years)
        run: |
          echo "🎄 Running all Advent of Code tests 🎄"
          echo "ADVENT_RUN_ALL_TESTS=$ADVENT_RUN_ALL_TESTS"
          uv run pytest python -v --tb=short
        env:
          ADVENT_RUN_ALL_TESTS: "True"
