# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11-dev
          cache: 'poetry'

      - name: Change poetry version
        working-directory: ./python
        run: |
          rm ./python/poetry.toml
          poetry env use python3.11

      - name: Install Dependencies
        working-directory: ./python
        run: poetry install

      - name: Code Quality
        working-directory: ./python
        run: |
          poetry check
          poetry run black --exclude .venv . --check
          poetry run mypy .
          poetry run flake8 .

      - name: Unit Tests
        working-directory: ./python
        run: |
          poetry run python -m pytest